#!/bin/sh
# Lets the user select an area of their screen with the mouse, which is then saved to `/tmp`
# with the current time, and then opened directly in Gimp, to allow for quick editing.

scrot -s '/tmp/%F_%T_$wx$h.png' -e 'gimp $f'
