#!/usr/bin/env bash
set -euo pipefail

# Short thing to stream various favorite Youtube streams from keywords

if [[ $# -eq 0 ]]; then
    echo "Youtube video ID: "
    read id
elif [[ $1 = "list" ]]; then
    echo -e "atmosambient | chillsynth | vaporfunk | jazz   | lofigirl | spaceambient\nnightride    | datawave   | retrowave | summer | starship | lofisynth"
    exit 1
elif [[ $1 = "jazz" ]]; then
    id="Dx5qFachd3A"
elif [[ $1 = "lofigirl" ]]; then
    id="jfKfPfyJRdk"
elif [[ $1 = "vaporfunk" ]]; then
    id="HuzAwhT3zQs"
elif [[ $1 = "chillsynth" ]]; then
    id="UedTcufyrHc"
elif [[ $1 = "retrowave" ]]; then
    id="9P23oE6ekwQ"
elif [[ $1 = "summer" ]]; then
    id="g1UVhexTLWU"
elif [[ $1 = "atmosambient" ]]; then
#    id="AEkEjX3P_S0"
    id="m4e1GYa_-iA"
elif [[ $1 = "nightride" ]]; then
    id="cZRj9Sk0IPc"
elif [[ $1 = "datawave" ]]; then
    id="Y9q6RYg2Pdg"
elif [[ $1 = "starship" ]]; then
    id="gpvznAiKblU"
elif [[ $1 = "lofisynth" ]]; then
    id="MVPTGNGiI-4"
elif [[ $1 = "spaceambient" ]]; then
    id="tNkZsRW7h2c"
else
    id=$1
fi

mpv --profile=stream --sub=no "https://youtube.com/watch?v=$id"
